{
	"version": 1587460263,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/plane-sheet0.png",
		"images/plane-sheet1.png",
		"images/plane-sheet2.png",
		"images/ground-sheet0.png",
		"images/rocktop-sheet0.png",
		"images/rocktop-sheet1.png",
		"images/rockbottom-sheet0.png",
		"images/rockbottom-sheet1.png",
		"images/puff-sheet0.png",
		"images/bggameover-sheet0.png",
		"images/tittle_gameover-sheet0.png",
		"images/btnreplay-sheet0.png",
		"images/star-sheet0.png",
		"images/getready-sheet0.png",
		"images/tapclick-sheet0.png",
		"images/sp_scoeplay.png",
		"images/bgblack-sheet0.png",
		"media/colider.m4a",
		"media/colider.ogg",
		"media/gameover.m4a",
		"media/gameover.ogg",
		"media/coin sound effect.m4a",
		"media/coin sound effect.ogg",
		"media/background.m4a",
		"media/background.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}