{
	"version": 1587461729,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/btnstart-sheet0.png",
		"images/icon_dhbc-sheet0.png",
		"images/alphabet-sheet0.png",
		"images/alphabet-sheet1.png",
		"images/alphabet-sheet2.png",
		"images/animals-sheet0.png",
		"images/animals-sheet1.png",
		"images/btnplay-sheet0.png",
		"images/boxchar-sheet0.png",
		"images/bggame-sheet0.png",
		"images/sp_scoregame.png",
		"images/imagesholder-sheet0.png",
		"images/replay-sheet0.png",
		"media/change-question.m4a",
		"media/change-question.ogg",
		"media/s-click_bt.m4a",
		"media/s-click_bt.ogg",
		"media/sound-correct.m4a",
		"media/sound-correct.ogg",
		"media/buzzer wrong answer .m4a",
		"media/buzzer wrong answer .ogg",
		"media/end_game.m4a",
		"media/end_game.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"hanhlang.jpg",
		"hoahau.jpg",
		"khaucung.jpg",
		"matma.jpg",
		"neodon.jpg"
	]
}